# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

services:
  - redis:latest
  - orientdb:latest

variables:
  ORIENTDB_ROOT_PASSWORD: testpassword
  ORIENTDB_PASSWORD: testpassword
  PRE_SHARED_KEY: testpsk
  ORIENTDB_DB: testdb
  ORIENTDB_USERNAME: root
  ORIENTDB_HOST: orientdb
  
cache:
  paths:
  - node_modules/

test_main:
  script:
   - git clone https://gitlab-ci-token:$CI_BUILD_TOKEN@openlab.ncl.ac.uk/gitlab/connected-academy/spec.git
   - npm install
   - npm test