# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

services:
  - redis:latest

variables:
  ORIENTDB_ROOT_PASSWORD: testpassword
  ORIENTDB_PASSWORD: testpassword
  PRE_SHARED_KEY: testpsk
  ORIENTDB_DB: testdb
  ORIENTDB_USERNAME: root
  ORIENTDB_HOST: orientdb
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  TWITTER_KEY: test
  TWITTER_SECRET: test
  GITHUB_CLIENT_ID: test
  GITHUB_CLIENT_SECRET: test
  TEST_DOMAIN: http://testclass.connectedacademy.io
  MASTER_REPO: https://connectedacademy.io/
  EDITOR_URI: http://prose.io/
  HOST: localhost

cache:
  paths:
  - node_modules/

stages:
  - test

test:
  stage: test
  script:
   - npm install
   - git clone https://gitlab-ci-token:$CI_BUILD_TOKEN@openlab.ncl.ac.uk/gitlab/connected-academy/spec.git
   - npm test