# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: docker:git
services:
  - docker:dind

variables:
  ORIENTDB_ROOT_PASSWORD: testpassword
  ORIENTDB_PASSWORD: testpassword
  PRE_SHARED_KEY: testpsk
  ORIENTDB_DB: testdb
  ORIENTDB_USERNAME: root
  ORIENTDB_HOST: orientdb
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  TWITTER_KEY: test
  TWITTER_SECRET: test
  GITHUB_CLIENT_ID: test
  GITHUB_CLIENT_SECRET: test
  TEST_DOMAIN: http://testclass.connectedacademy.io
  MASTER_REPO: https://connectedacademy.io/
  EDITOR_URI: http://prose.io/
  HOST: localhost

cache:
  paths:
  - node_modules/

# test:
#   tags:
#     - local
#   stage: test
#   services:
#     - redis:latest
#   script:
#     - docker pull $CONTAINER_TEST_IMAGE
#     - docker run $CONTAINER_TEST_IMAGE npm test

stages:
- build
# - test
- release
- deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  CONTAINER_DOCKERHUB_RELEASE: connectedacademy/watercooler:latest

before_script:
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" $CI_REGISTRY

build:
  stage: build
  tags:
    - local
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - master

gitlab-repository:
  stage: release
  tags:
    - local
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

dockerhub:
  stage: release
  tags:
    - local
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker login -u $DOCKER_USERNAME -p "$DOCKER_PASSWORD"
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_DOCKERHUB_RELEASE
    - docker push $CONTAINER_DOCKERHUB_RELEASE
  only:
    - master

deploy-aws:
  stage: deploy
  environment: amazonlive
  image: ruby:latest
  when: manual
  script:
    - gem install dpl
    - dpl --provider=elasticbeanstalk --access-key-id=<access-key-id> --secret-access-key="<secret-access-key>" --app="example-app-name" --env="example-app-environment" --region="us-west-2"
  only:
    - master