version: '2'
networks:
  dev_ca-back-network:
    external: true
    
services:
  watercooler:
    build: .
    volumes:
      - ./api:/usr/src/app/api
      - ./config:/usr/src/app/config
    command: nodemon -x "node --harmony-async-await" -L app.js
    ports:
      - "4000:1337"
    networks: 
      - dev_ca-back-network
    env_file: .env