version: '2'
networks:
  dev_ca-back-network:
    external: true
    
services:
  watercooler:
    build: .
    volumes:
      - ./api:/usr/src/app/api
      - ./config:/usr/src/app/config
      - ./views:/usr/src/app/views
      - ./test:/usr/src/app/test:ro
      - ./.sailsrc:/usr/src/app/.sailsrc
      - ../spec:/usr/src/app/spec:ro
    command: nodemon --debug=0.0.0.0:5858 -x "node --harmony-async-await" -L app.js
    ports:
      - "4000:1337"
      - "5858:5858"
    networks: 
      - dev_ca-back-network
    env_file: .env
  # test:
  #   image: connectedacademy/watercooler
  #   env_file: .env
  #   depends_on:
  #     - orientdb
  #     - redis
  #   environment:
  #     - NODE_ENV=production
  # orientdb:
  #   image: orientdb
  #   environment:
  #     - ORIENTDB_ROOT_PASSWORD=BlahBlah123
  #     - ORIENTDB_NODE_NAME=odb1
  # redis:
  #   image: redis