var passport = require('passport');
module.exports.policies = {
    '*':['verifyDomain','jsononly','cors'],
    'auth':
    {
        'root':[true],
        'login':['verifyDomain'],
        'admin':['verifyDomain'],
        'twitter_callback':[true],
        'github_callback':[true],
        'dashboard':['isUser',true],
        'admindashboard':['verifyDomain','isAdmin',true],        
        'fail':[true],
        'logout':[true],
        'admin_logout':[true],
        'me':['verifyDomain','jsononly','cors'],
        'profile':['isUser','verifyDomain','jsononly','cors'],
        'register':['isUser','verifyDomain','jsononly','cors'],
        'testadminlogin':['verifyDomain'],
        'testuserlogin':['verifyDomain']
    },
    'admin':
    {
        '*':['verifyDomain','isAdmin','jsononly','cors'],
        'editor':['verifyDomain']
    },
    'messages':
    {
        '*':['isUser','verifyDomain','jsononly','cors']
    },
    'classroom':
    {
        '*':['isUser','verifyDomain','jsononly','cors']
    },
    'analytics':
    {
        'submit':['isUser','verifyDomain','jsononly','cors'],
        'question':['isUser','verifyDomain','jsononly','cors'],
        'answers':['verifyDomain','isAdmin','jsononly','cors']
    }
};